name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs_on: python:3.12-slim
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the Image
        run: |
          docker login --username creadesk --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/creadesk/privycloud:latest
          docker push ghcr.io/creadesk/privycloud:latest